### ISSUE TITLE
How to compile a python installation package for Mac M1 (arm64)?

### ISSUE THREAD

**Issue by yoummiegao** [jrast/littlefs-python#13]
Hi, 
I'm a freshman for python development and try to develop some project in a macbook m1 with tensorflow and littlefs. May I know how to compile a python installation package of littlefs-python to fit into m1 arm64 arch?
Thank you so much!

**Comment by jrast** [comment]
I don't know anything about building python extensions on Mac, so I cannot really help...
You probably need to install the dependencies required by Cython (which is used to build the package / littlefs) as described here: https://cython.readthedocs.io/en/stable/src/quickstart/install.html

Cython itself should be installed automatically but the compiler must be installed manually.

Let me know of your progress! If you add the required steps to compile on mac to this issue I will update the readme accordingly.

**Comment by yoummiegao** [comment]
Hi jrast,

Thank you so much for your prompt reply.

> I don't know anything about building python extensions on Mac, so I cannot really help... You probably need to install the dependencies required by Cython (which is used to build the package / littlefs) as described here: https://cython.readthedocs.io/en/stable/src/quickstart/install.html
> 
> Cython itself should be installed automatically but the compiler must be installed manually.
> 
> Let me know of your progress! If you add the required steps to compile on mac to this issue I will update the readme accordingly.

I think currently my env is ready including Cython, tensorflow (to align issue related env) and compiler gcc (actually Apple clang 14.0.0), so what should I do next? Could you help guide shell operations, etc. to process rest of compiling? enter the littlefs folder to execute make command or something else to build this installation package for m1 mac?

`(tf26_m1) MacBook-Pro:littlefs-python yoummiegao$ gcc -v
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(tf26_m1) MacBook-Pro:littlefs-python fenggao$ python
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:55:15)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> import cython
>>> import littlefs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fenggao/Downloads/littlefs-python/src/littlefs/__init__.py", line 7, in <module>
    from . import errors, lfs
ImportError: dlopen(/Users/fenggao/Downloads/littlefs-python/src/littlefs/lfs.cpython-39-darwin.so, 0x0002): tried: '/Users/fenggao/Downloads/littlefs-python/src/littlefs/lfs.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
>>>`

**Comment by jrast** [comment]
It seems like there went something wrong during installation as the `*.so` file has the wrong architecture (x86_64 instead of arm64e). Can you try this: https://stackoverflow.com/a/72009173/1211607, of course with the littlefs-python package. So something like this:

```
pip uninstall littlefs-python
arch -arm64 python3 -m pip install littlefs-python
```

**Comment by yoummiegao** [comment]
Hi jrast,

Other related issues show out when executing above two commands

>pip uninstall littlefs-python
arch -arm64 python3 -m pip install littlefs-python

so issues are shown like

> (tf26_m1) MacBook-Pro:littlefs-python fenggao$ pip uninstall littlefs-python
Found existing installation: littlefs-python 0.3.1.dev7+gd5a7ee2
Uninstalling littlefs-python-0.3.1.dev7+gd5a7ee2:
  Would remove:
    /Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/littlefs-python.egg-link
Proceed (Y/n)? Y
  Successfully uninstalled littlefs-python-0.3.1.dev7+gd5a7ee2
(tf26_m1) MacBook-Pro:littlefs-python fenggao$ arch -arm64 python3 -m pip install littlefs-python
Collecting littlefs-python
  Downloading littlefs-python-0.3.0.tar.gz (225 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.4/225.4 kB 198.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: littlefs-python
  Building wheel for littlefs-python (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-39
      creating build/lib.macosx-11.0-arm64-cpython-39/littlefs
      copying src/littlefs/__init__.py -> build/lib.macosx-11.0-arm64-cpython-39/littlefs
      copying src/littlefs/context.py -> build/lib.macosx-11.0-arm64-cpython-39/littlefs
      copying src/littlefs/errors.py -> build/lib.macosx-11.0-arm64-cpython-39/littlefs
      running build_ext
      building 'littlefs.lfs' extension
      creating build/temp.macosx-11.0-arm64-cpython-39
      creating build/temp.macosx-11.0-arm64-cpython-39/littlefs
      creating build/temp.macosx-11.0-arm64-cpython-39/src
      creating build/temp.macosx-11.0-arm64-cpython-39/src/littlefs
      clang -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/fenggao/miniforge3/envs/tf26_m1/include -arch arm64 -fPIC -O2 -isystem /Users/fenggao/miniforge3/envs/tf26_m1/include -arch arm64 -DLFS_NO_DEBUG=1 -DLFS_NO_WARN=1 -DLFS_NO_ERROR=1 -Ilittlefs -I/Users/fenggao/miniforge3/envs/tf26_m1/include/python3.9 -c littlefs/lfs.c -o build/temp.macosx-11.0-arm64-cpython-39/littlefs/lfs.o -std=c99
      littlefs/lfs.c:429:13: warning: unused function 'lfs_mlist_isopen' [-Wunused-function]
      static bool lfs_mlist_isopen(struct lfs_mlist *head,
                  ^
      1 warning generated.
      clang -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/fenggao/miniforge3/envs/tf26_m1/include -arch arm64 -fPIC -O2 -isystem /Users/fenggao/miniforge3/envs/tf26_m1/include -arch arm64 -DLFS_NO_DEBUG=1 -DLFS_NO_WARN=1 -DLFS_NO_ERROR=1 -Ilittlefs -I/Users/fenggao/miniforge3/envs/tf26_m1/include/python3.9 -c littlefs/lfs_util.c -o build/temp.macosx-11.0-arm64-cpython-39/littlefs/lfs_util.o -std=c99
      clang -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/fenggao/miniforge3/envs/tf26_m1/include -arch arm64 -fPIC -O2 -isystem /Users/fenggao/miniforge3/envs/tf26_m1/include -arch arm64 -DLFS_NO_DEBUG=1 -DLFS_NO_WARN=1 -DLFS_NO_ERROR=1 -Ilittlefs -I/Users/fenggao/miniforge3/envs/tf26_m1/include/python3.9 -c src/littlefs/lfs.c -o build/temp.macosx-11.0-arm64-cpython-39/src/littlefs/lfs.o -std=c99
      clang -pthread -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/fenggao/miniforge3/envs/tf26_m1/lib -L/Users/fenggao/miniforge3/envs/tf26_m1/lib -Wl,-rpath,/Users/fenggao/miniforge3/envs/tf26_m1/lib -L/Users/fenggao/miniforge3/envs/tf26_m1/lib build/temp.macosx-11.0-arm64-cpython-39/littlefs/lfs.o build/temp.macosx-11.0-arm64-cpython-39/littlefs/lfs_util.o build/temp.macosx-11.0-arm64-cpython-39/src/littlefs/lfs.o -o build/lib.macosx-11.0-arm64-cpython-39/littlefs/lfs.cpython-39-darwin.so
      /Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.macosx-11.0-arm64/wheel
      running install
      running install_lib
      creating build/bdist.macosx-11.0-arm64
      creating build/bdist.macosx-11.0-arm64/wheel
      creating build/bdist.macosx-11.0-arm64/wheel/littlefs
      copying build/lib.macosx-11.0-arm64-cpython-39/littlefs/lfs.cpython-39-darwin.so -> build/bdist.macosx-11.0-arm64/wheel/littlefs
      copying build/lib.macosx-11.0-arm64-cpython-39/littlefs/__init__.py -> build/bdist.macosx-11.0-arm64/wheel/littlefs
      copying build/lib.macosx-11.0-arm64-cpython-39/littlefs/context.py -> build/bdist.macosx-11.0-arm64/wheel/littlefs
      copying build/lib.macosx-11.0-arm64-cpython-39/littlefs/errors.py -> build/bdist.macosx-11.0-arm64/wheel/littlefs
      running install_egg_info
      running egg_info
      writing src/littlefs_python.egg-info/PKG-INFO
      writing dependency_links to src/littlefs_python.egg-info/dependency_links.txt
      writing top-level names to src/littlefs_python.egg-info/top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'src/littlefs_python.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching 'src' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
      warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
      adding license file 'LICENSE'
      writing manifest file 'src/littlefs_python.egg-info/SOURCES.txt'
      Copying src/littlefs_python.egg-info to build/bdist.macosx-11.0-arm64/wheel/littlefs_python-0.3.0-py3.9.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/cx/459mmr7s3dx7kbc9n5r7q0f00000gn/T/pip-install-dpr85ok9/littlefs-python_4d8777975def4459ac25cb3b63274842/setup.py", line 31, in <module>
          setup(
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/Users/fenggao/miniforge3/envs/tf26_m1/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
      AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_arm64')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for littlefs-python
  Running setup.py clean for littlefs-python
Failed to build littlefs-python
Installing collected packages: littlefs-python
  Running setup.py install for littlefs-python ... done
  DEPRECATION: littlefs-python was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368

**Comment by yoummiegao** [comment]
> It seems like there went something wrong during installation as the `*.so` file has the wrong architecture (x86_64 instead of arm64e). Can you try this: https://stackoverflow.com/a/72009173/1211607, of course with the littlefs-python package. So something like this:
> 
> ```
> pip uninstall littlefs-python
> arch -arm64 python3 -m pip install littlefs-python
> ```
> 
> No idea if this will help...

Hi jrast,
After executing **_python -m pip install wheel setuptools pip --upgrade_**
then follows above two commands
`pip uninstall littlefs-python`
`arch -arm64 python3 -m pip install littlefs-python`

Finally, it really works for me

> (tf26_m1) MacBook-Pro:littlefs-python fenggao$ python
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:55:15)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import littlefs
>>>

Thank you so much!

**Comment by jrast** [comment]
@yoummiegao Great that you where able to find a solution! So in short, if this would be added to the readme, other people should be able to build the package on Mac M1 (ARM Arch):

1. Install a compiler. One option is XCode (https://developer.apple.com/). See also https://cython.readthedocs.io/en/stable/src/quickstart/install.html
2. Install the package. As no wheels are provided for M1 processors, the package will be built on the fly:
```bash
# Make sure you have an up to date version of wheel / setuptools / pip
python -m pip install --upgrade wheel setuptools pip
# build the package with arm64
arch -arm64 python -m pip install littlefs-python
```
