### ISSUE TITLE
Incompatible with littlefs 2.5.0

### ISSUE THREAD

**Issue by rift-labs-developer** [jrast/littlefs-python#21]
Littlefs 2.5.0 on our zephyr mcu was unable to open images created using this package. It was working fine with 2.4.0.
I dont have any more details, as I have not debugged this myself.

**Comment by jrast** [comment]
Basically this should work as Version 2.4.1 (which is used by littlefs-python) should be compatible with version 2.5.0 which you use. Please provide more information about what worked, what was not working, ...

**Comment by jrast** [comment]
Closing this as no evidence / steps to reproduce / example is provided. Please reopen if this is still an issue and steps to reproduce are provided.
