### ISSUE TITLE
Error messages occur when I install littlefs-python

### ISSUE THREAD

**Issue by Femtometer** [jrast/littlefs-python#3]
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads

**Comment by Femtometer** [comment]
Using Windows7 64bits OS

**Comment by irmen** [comment]
So, have you tried the suggestion the error gives you?

**Comment by jrast** [comment]
@Femtometer how do you try to install littlefs? If you install from the source, a compiler is required.
