### ISSUE TITLE
FS version inconsistency / pinning

### ISSUE THREAD

**Issue by bwhitman** [jrast/littlefs-python#35]
I am using littlefs-python to generate the filesystem in [Tulip](/bwhitman/tulipcc), which is based on [Micropython](/micropython/micropython). 

I recently had an issue with this setup as the littlefs-python module was installed a new machine to 0.5.0. This breaks Micropython/Tulip as it's expecting a LFS version <2.1, we get `littlefs/lfs2.c:4148:error: Invalid version v2.1`. I'm able to upgrade Micropython's LFS version, or skip the check, so this is not a blocking issue. But [I see on your chart](https://github.com/jrast/littlefs-python#installation) that 0.5.0 should be LittleFS version 2.4.1 and FS version 2.0, but that seems incorrect - -[your release notes for 0.5.0](https://github.com/jrast/littlefs-python/releases/tag/0.5.0) indicate you've bumped LittleFS to 2.6.1 / 2.1, and my testing indicates the same -- it's generating a 2.1 FS. 

If you agree, I can submit a PR to fix the chart. But in general, is it or should it be possible to pin littlefs-python to an FS version? e.g. when creating the FS: `cfg = lfs.LFSConfig(block_size=4096, block_count = VFS_SIZE / 4096, littefs_version="2.0")` This would avoid incompatibilities with older embedded things that are harder or slower to upgrade.

**Comment by jrast** [comment]
Point is: There is no Release 0.6.0 as shown in overview in the readme... I fixed the table.

Supporting multiple FS Versions sounds rather complex, but I'm happy to accept a PR as this is definitely something which would be nice.

**Comment by Krakonos** [comment]
@bwhitman is correct that it's another option in config and it should be relatively straightforward to pass this through the python interface. Unless somebody is faster, I'll have a look into a PR for that.

**Comment by jrast** [comment]
I don't see a option for LittleFS to set the version? But sure, if it's possible to configure the version, go a head!

**Comment by Krakonos** [comment]
This is a new option in v2.7, see release notes: https://github.com/littlefs-project/littlefs/releases/tag/v2.7.0 . I guess this change caused issues to a lot of people, as it breaks the tooling made for preparing images - and in some cases, upgrade just isn't possible (as an example, a non-upgradable bootloader only supports lfs format 2.0).

**Comment by Krakonos** [comment]
I just submitted 3 PRs, #40, #41 and #42 that implement the disk_version option, allowing of version selection in `LFSConfig`.

**Comment by jrast** [comment]
Merged the mentioned PRs.

**Comment by Krakonos** [comment]
@jrast Thanks for merging those PRs, however I think before this issue is fully complete a release is required so we can easily reference the required version in dependencies.

**Comment by jrast** [comment]
A new release is in progress: https://github.com/jrast/littlefs-python/actions/runs/5783393434

**Comment by jrast** [comment]
@Krakonos: It seems like the build is hanging... No idea why.

**Comment by jrast** [comment]
The new release is out: https://pypi.org/project/littlefs-python/0.6.2/
Had to fix some issues in the build pipeline and I hope all relevant wheels where built...
