### ISSUE TITLE
No 0.1.3 source in PyPI

### ISSUE THREAD

**Issue by sTywin** [jrast/littlefs-python#5]
There is no `littlefs-python-0.1.3.tar.gz` in the PyPI release, meaning it does not `pip install` for me on macOS.

**Comment by jrast** [comment]
Oh sorry... I'll look into this! Should be available in a few / couple minutes.

**Comment by jrast** [comment]
Ok, should be there now. Can you check if the installation works for you?

**Comment by sTywin** [comment]
Confirmed, present and installs for me now, thank you :)
