### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by DvdGiessen** [jrast/littlefs-python#66]
Ran into errors trying to use `littlefs-python` in a project using the [the `pdm` package manager](https://github.com/pdm-project/pdm):

```
Traceback (most recent call last):
  (redacted)
  File "(redacted)/.venv/lib/python3.11/site-packages/littlefs/__init__.py", line 5, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

It seems this package is depending on `setuptools`, which isn't part of core Python, but doesn't declare it as a dependency.

Since PDM (and some other Python tools too) manage the virtual environment without having `setuptools`(or `pip` for that matter) installed, using `littlefs-python` fails with the above error.

Also from what I can tell Python since 3.12 is no longer including `setuptools` by default. From the release notes:
> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment.

So we should probably add `setuptools` to the list of dependencies?

Note that for the runtime part we could also consider switching to `importlib` (see for example https://github.com/sphinx-doc/sphinx/pull/10007).

<details><summary>Change for that would probably look a bit like this.</summary>

Add `"importlib-metadata>=4.4; python_version < '3.10'"` as dependency for compat with older Python versions.

```diff
diff --git a/docs/conf.py b/docs/conf.py
index 703d352..c1adb45 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -12,9 +12,12 @@ copyright = "2019 - 2023, Jürg Rast"
 author = "Jürg Rast"
 
 # The full version, including alpha/beta/rc tags
-from pkg_resources import get_distribution
+try:
+    from importlib_metadata import version as importlib_metadata_version
+except ImportError:
+    from importlib.metadata import version as importlib_metadata_version
 
-version = get_distribution("littlefs-python").version
+version = importlib_metadata_version("littlefs-python")
 release = version
 
 # The master doc must be set for read the docs.
diff --git a/src/littlefs/__init__.py b/src/littlefs/__init__.py
index cdcb107..86c2c0f 100644
--- a/src/littlefs/__init__.py
+++ b/src/littlefs/__init__.py
@@ -2,7 +2,10 @@ import io
 import warnings
 from typing import TYPE_CHECKING, List, Tuple, Iterator, IO, Union, Optional
 
-from pkg_resources import DistributionNotFound, get_distribution
+try:
+    from importlib_metadata import version, PackageNotFoundError
+except ImportError:
+    from importlib.metadata import version, PackageNotFoundError
 
 from . import errors, lfs
 from .lfs import __LFS_DISK_VERSION__, __LFS_VERSION__
@@ -10,8 +13,8 @@ from .errors import LittleFSError
 
 
 try:
-    __version__ = get_distribution('littlefs-python').version
-except DistributionNotFound:
+    __version__ = version('littlefs-python')
+except PackageNotFoundError:
     # Package not installed
     pass
 
```
</details>

**Comment by BrianPugh** [comment]
`v0.9.0` has been released and should resolve this issue.
