### ISSUE TITLE
Data disappearing after flashing the bin file

### ISSUE THREAD

**Issue by harsh04** [jrast/littlefs-python#84]
Hi, I followed the following steps to create a bin file for esp32 but still I am getting error that file not found.
1. I created a config.json file and then I used it to create a bin file using the following command:
```littlefs_create -b 4096 -c 256 -i test.bin -s dist/b```
using the below command I confirmed if that test.bin contains config.json or not
```littlefs_list -b 4096 -c 256 -i test.bin  ```

2. then I used to following command to flash the test.bin to esp32.
```esptool.py --port /dev/cu.usbserial-567F0302541 --baud 115200 write_flash -z 0x210000 test.bin```

3. When I restart the ESP32, it does not detect config.json in the designated storage.

To narrow down the root cause, this time I created config.json inside the esp32 itself and exported it to bin file using this command:
``` esptool.py --port /dev/cu.usbserial-567F0302541 --baud 115200 read_flash 0x210000 0x100000 out.bin```
and I checked for config.json using ```littlefs_list -b 4096 -c 256 -i out.bin  ```, I could see the config.json inside it. This time I flashed out.bin using the same esptool.py command and it worked. the esp32 was able to read the file.
So I compared the test.bin file that i created using littlefs_create and the out.bin file that was created inside the esp32. They both are different, though the content used inside config.json was the same in both places.
I am really unable to understand what i am doing wrong or how can i fix it? Please suggest.

**Comment by BrianPugh** [comment]
can you give more environment details and runtime logs? Are you using [esp_littlefs](https://github.com/joltwallet/esp_littlefs)? If so, what version of esp_littlefs? What version of littlefs-python? If this is esp_littlefs, please open an issue in that repo; we can bring the discussion back over here if it's determined to be an upstream littlefs-python issue.

**Comment by harsh04** [comment]
Hi, I am not using esp_littlefs but LittleFS_esp32 by lorol on esp32. and littlefs-python==0.9.3

**Comment by BrianPugh** [comment]
[Lorol's repo](https://github.com/lorol/LITTLEFS) is based on esp_littlefs, but is pretty old and not exactly maintained (last release Aug 2021):

> Ths library is now part of [Arduino esp32 core v2](https://github.com/espressif/arduino-esp32/tree/master/libraries/LittleFS)
Note, there it is renamed from LITTLEFS to LittleFS, Please post your issues there. This here is kept for Arduino esp32 core 1.x purposes

It seems like it was last updated to littlefs v2.4.0. In littlefs v2.6 the on-disk version spec was bumped to 2.0 to 2.1. In the release notes it says this:
> This change is backwards-compatible, but after the first write with the new version, the image on disk will no longer be mountable by older versions of littlefs.

I would recommend updating to a more modern version of littlefs on your esp32.

Alternatively, you need to pass in `disk_version=0x00020000` [to your `LFSConfig` definition](https://github.com/jrast/littlefs-python/blob/664b72f50c311d139acae8865bffd48b348d3d49/src/littlefs/lfs.pyx#L107).

This currently is not exposed int he bundled CLI, but we'd accept a PR making it so.

**Comment by BrianPugh** [comment]
closing this issue for now; please comment if you believe this issue was closed prematurely.
